### ISSUE TITLE
disable cat speak

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#498]
### Summary

add the option to disable talking like a cat while still being a cat

### Purpose

it would be very nice to have a cat account without having my post text edited (especially for serious posts)

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
<img width="408" alt="image" src="https://github.com/user-attachments/assets/5ae76f95-9df4-4bb6-b6cc-6b5cc59b41aa">

Although it is not a desired feature, CherryPick currently has a feature that allows you to disable Nyaization applied to notes.
Of course, this feature does not apply to Misskey-based clients other than CherryPick, so Misskey-based clients will still see Nyaization applied.

This issue is due to the way Misskey-based clients receive notes as raw and then apply Nyaization locally, so if your account is a cat, they will still show Nyaization. (At some point, Misskey's Nyaization method changed from destructively modifying notes to receiving them without changing the note content and then applying Nyaization locally.)

Non-Misskey clients such as Mastodon do not apply Nyaization, so they are relatively free from this problem.

**Comment by breadguyyy** [comment]
oh I see, if it's just client side then no worries. thank you for the info!

**Comment by breadguyyy** [comment]
this seems like a non issue so I'll go ahead and close
